<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>false</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.101.6" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="DotnetGeminiSDK" Version="1.0.14" />
    <PackageReference Include="Google.Ads.GoogleAds" Version="22.0.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.57" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MimeTypes" Version="2.5.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MySqlConnector" Version="2.1.13" />
    <PackageReference Include="SSH.NET" Version="2020.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.3.1" />
    <PackageReference Include="Syncfusion.DocIORenderer.Net.Core" Version="27.1.55" />
    <PackageReference Include="Syncfusion.Pdf.Net.Core" Version="27.1.55" />
    <PackageReference Include="Syncfusion.PDF.OCR.Net.Core" Version="27.1.55" />
    <PackageReference Include="Syncfusion.Presentation.Net.Core" Version="27.1.55" />
    <PackageReference Include="Syncfusion.PresentationRenderer.Net.Core" Version="27.1.55" />
    <PackageReference Include="System.Data.OleDb" Version="7.0.0" />
    <PackageReference Include="Twilio" Version="5.75.0" />
  </ItemGroup>


</Project>
